#
# -------------------------------------------
# SPRING配置
# -------------------------------------------
#
spring:
  cache:
    type: redis
  redis:
    timeout: 5000
    lettuce:
      pool:
        # 连接池最大阻塞等待时间 单位毫秒 ms
        max-wait: 5000
        # 连接池最大连接数
        max-active: 200
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
