#
# -------------------------------------------
# SPRING配置
# -------------------------------------------
#
spring:
  cache:
    type: redis
  redis:
    timeout: 5000
    lettuce:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: 5000
        min-idle: 0
        time-between-eviction-runs: 1m
        shutdown-timeout: 500ms
